-- 备份记录表
CREATE TABLE IF NOT EXISTS `sys_backups` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '备份ID',
    `backup_name` VARCHAR(200) NOT NULL COMMENT '备份名称',
    `backup_type` VARCHAR(50) NOT NULL COMMENT '备份类型:database,file,full,incremental',
    `file_path` VARCHAR(500) COMMENT '备份文件路径',
    `file_size` BIGINT COMMENT '备份文件大小(字节)',
    `base_backup_id` BIGINT COMMENT '基础备份ID(增量备份时使用)',
    `status` VARCHAR(50) NOT NULL DEFAULT 'pending' COMMENT '备份状态:pending,running,completed,failed,deleted,cancelled',
    `description` VARCHAR(500) COMMENT '备份描述',
    `start_time` DATETIME COMMENT '开始时间',
    `end_time` DATETIME COMMENT '完成时间',
    `duration` BIGINT COMMENT '备份耗时(毫秒)',
    `operator_id` BIGINT COMMENT '操作人ID',
    `operator_name` VARCHAR(100) COMMENT '操作人名称',
    `error_message` VARCHAR(1000) COMMENT '错误信息(备份失败时)',
    `verified` BOOLEAN DEFAULT FALSE COMMENT '是否已验证',
    `verified_time` DATETIME COMMENT '验证时间',
    `verified_result` VARCHAR(500) COMMENT '验证结果',
    `storage_type` VARCHAR(50) DEFAULT 'local' COMMENT '存储类型:local,oss,s3',
    `storage_config` VARCHAR(1000) COMMENT '存储配置(JSON)',
    `progress` INT DEFAULT 0 COMMENT '备份进度(0-100)',
    `restorable` BOOLEAN DEFAULT TRUE COMMENT '是否可恢复',
    `retention_days` INT DEFAULT 30 COMMENT '保留天数',
    `expiry_time` DATETIME COMMENT '过期时间',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `md5` VARCHAR(32) COMMENT '备份文件MD5',
    `sha256` VARCHAR(64) COMMENT '备份文件SHA256',
    `encrypted` BOOLEAN DEFAULT FALSE COMMENT '是否加密',
    `included_tables` VARCHAR(2000) COMMENT '备份包含的表(JSON数组)',
    `database_name` VARCHAR(100) COMMENT '备份的数据库名称',
    `deleted` BOOLEAN DEFAULT FALSE COMMENT '是否删除',
    INDEX `idx_backup_type` (`backup_type`),
    INDEX `idx_status` (`status`),
    INDEX `idx_created_at` (`created_at`),
    INDEX `idx_operator_id` (`operator_id`),
    INDEX `idx_expiry_time` (`expiry_time`),
    INDEX `idx_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统备份记录表';

